name: Terraform Destroy

on:
   schedule:
     - cron: '0 0 * * *'  # Runs Everyday at Midnight

jobs:
   terraform-destroy:
    runs-on: ubuntu-latest
    
    steps:
    - name: "Checkout"
      uses: actions/checkout@master

    - name: Multi-Line Script
      run: |
        echo Hello, Vamsi!
        echo Running Terraform Destroy.

    - name: "Terraform Init"
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 0.12.26
        tf_actions_subcommand: 'init'
      env:
        TF_CLI_ARGS_init: '-backend-config="access_key=${{ secrets.ACCESS_KEY }}"'
      
    - name: "Terraform Destroy"
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 0.12.26
        tf_actions_subcommand: "destroy"
        args: '-var="client_id=${{ secrets.CLIENT_ID }}" -var="client_secret=${{ secrets.CLIENT_SECRET }}" -var="subscription_id=${{ secrets.SUBSCRIPTION_ID }}" -var="tenant_id=${{ secrets.TENANT_ID }}"'
